<?php
// =====================================================================
//  MAHINDO - MAIL SETTINGS (reads your .env file - you do not edit this file)
//
//  Put your passwords in a file named  .env  (copy .env.example -> .env).
//  Best place on Hostinger: ONE FOLDER ABOVE public_html  (e.g. /home/uXXXX/domains/mahindo.in/.env)
//  Also works: inside public_html next to this file (the .htaccess blocks it from browsers).
// =====================================================================
if (!defined('MAHINDO_MAIL')) { http_response_code(403); exit; }

function mh_load_env() {
    $env = [];
    $dir = __DIR__;
    $candidates = [dirname($dir) . '/.env', dirname(dirname($dir)) . '/.env', $dir . '/.env'];
    foreach ($candidates as $f) {
        if (!is_file($f) || !is_readable($f)) continue;
        foreach (file($f, FILE_IGNORE_NEW_LINES) as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#' || strpos($line, '=') === false) continue;
            list($k, $v) = explode('=', $line, 2);
            $k = trim($k); $v = trim($v);
            if (strlen($v) >= 2 && ($v[0] === '"' || $v[0] === "'") && substr($v, -1) === $v[0]) $v = substr($v, 1, -1);
            $env[$k] = $v;
        }
        break; // first .env found wins
    }
    return $env;
}
$E = mh_load_env();
$g = function ($k, $d = '') use ($E) { return (isset($E[$k]) && $E[$k] !== '') ? $E[$k] : $d; };

return [
    'host'     => $g('SMTP_HOST', 'smtp.hostinger.com'),
    'port'     => (int)$g('SMTP_PORT', '465'),
    'secure'   => $g('SMTP_SECURE', 'ssl'),          // ssl (465) | tls (587) | none
    'test_key' => $g('TEST_KEY', ''),
    'accounts' => [
        'sales' => [
            'user'      => $g('SALES_USER', 'sales@mahindo.in'),
            'pass'      => $g('SALES_PASS', 'PUT_SALES_MAILBOX_PASSWORD_HERE'),
            'from_name' => 'Mahindo Website - Quote Request',
            'to'        => $g('SALES_TO', 'sales@mahindo.in'),
        ],
        'hr' => [
            'user'      => $g('HR_USER', 'hr@mahindo.in'),
            'pass'      => $g('HR_PASS', 'PUT_HR_MAILBOX_PASSWORD_HERE'),
            'from_name' => 'Mahindo Website - Career Application',
            'to'        => $g('HR_TO', 'hr@mahindo.in'),
        ],
    ],
];
